version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017'

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: node-api
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - PORT=5000
    volumes:
      - /app/node_modules
      - F:/Marek/ug/technologie-chmurowe/lab06/zad03/backend:/app
    ports:
      - '5000'
    depends_on:
      - mongo
    links:
      - mongo

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: react-app
    environment:
      - REACT_APP_SERVER_HOST=localhost
      - REACT_APP_SERVER_PORT=3000/api
      - CHOKIDAR_USEPOLLING="true"
    volumes:
      - /app/node_modules
      - F:/Marek/ug/technologie-chmurowe/lab06/zad03/frontend:/app
    ports:
      - '3000'
    depends_on:
      - backend
    links:
      - backend

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: nginx-server
    ports:
      - '3000:80'