apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-development-mongo-local

spec:
  storageClassName: manual
  claimRef:
    namespace: development
    name: mongo-development-pvc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /development/mongo/data