apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: mongo-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi