apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-db
  labels:
    app: mypostgres
    type: db

spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        app: mypostgres
        type: db

    spec: 
      containers:
        - name: mypostgres-container
          image: postgres:alpine
          env: 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PGPASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: PGDATABASE
           
  replicas: 1
  selector:
    matchLabels:
      app: mypostgres
      type: db