apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/f/Marek/ug/technologie-chmurowe/lab10/zad04/data