apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
spec:
  selector:
    matchLabels:
      tier: frontend

  replicas: 2
  template: 
    metadata:
      labels: 
        tier: frontend
    spec:
     containers:
     - name: front
       image: front:release1