apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-production-mongo-local
  labels:
    type: local

spec:
  storageClassName: manual
  claimRef:
    namespace: production
    name: mongo-production-pvc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /production/mongo/data