apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: mongo-production-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Mi