apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: pv-mongo-local
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/mongo/data