apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontend
spec:
  selector:
    matchLabels:
      tier: frontend

  replicas: 1
  template: 
    metadata:
      labels: 
        tier: frontend
    spec:
     containers:
     - name: nginx
       image: nginx:react