version: '3'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - '6379:6379'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: node-api
    volumes:
      - /app/node_modules
      - F:/Marek/ug/technologie-chmurowe/lab06/zad01/backend:/app
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - PGPORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - redis
    links:
      - redis