version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-server
    ports:
      - '27017:27017'

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: node-api
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    links:
      - mongo

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: react-app
    environment:
      - SERVER_URL=backend
      - SERVER_PORT=4000
    ports:
      - '3000:80'
    depends_on:
      - backend
    links:
      - backend